# Generated by Django 3.2.3 on 2021-08-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_auto_20210810_2134"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Question",
            new_name="QuestionBase",
        ),
    ]
