# Generated by Django 3.2.3 on 2021-08-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_rename_question_questionbase"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbase",
            name="points_count",
            field=models.IntegerField(default=0),
        ),
    ]
